repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat
        name: djLint formatting
        entry: djlint --reformat
        types_or: [html]
        language: python
      - id: djlint-jinja
        name: djLint linting for Jinja
        entry: djlint --profile=jinja
        types_or: [html]
        language: python
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
